todo_list/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos
end

todo_list/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

todo_list/app/models/todo.rb
class Todo < ApplicationRecord
	validates_presence_of :title, :due_date
	validates :title, length: { maximum: 20 }

end

todo_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

todo_list/app/controllers/todos_controller.rb
class TodosController < ApplicationController

	def index
		@todos = Todo.all
		@todos = Todo.order(due_date: :asc)

	end

	def new
		@todo = Todo.new

	end

	def create
		@todo = Todo.new(todo_params)
		if @todo.save
			redirect_to todos_path   #重新發出request，會重整頁面
			flash[:notice] = "List was successfully created !!"

		else
			render :action => :new   #保留需求不會清空資料，使用者可以繼續填寫錯誤的部分

		end
		
	end

	def edit
		@todo = Todo.find(params[:id])
		
	end

	def update
		@todo = Todo.find(params[:id])
		@todo.update(todo_params)
		flash[:notice] = "List was successfully updated !!"

		redirect_to todos_path
		
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		flash[:alert] = "List was successfully deleted !!"

		redirect_to todos_path
		
	end

	private

	def todo_params
		params.require(:todo).permit(:title, :due_date)
		
	end

end

todo_list/app/helpers/application_helper.rb
module ApplicationHelper
end

todo_list/app/helpers/todos_helper.rb
module TodosHelper
end

todo_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

		<style>
			body{
				position: relative;
			}
			.amendmsg{
				width: 300px;
				height: 30px;

				line-height: 20px;

				/*border: solid 1px black;*/
				display: inline-block;
				position: absolute;
				
				right: 50%;
				transform: translate(70%, 50%);
				z-index: 1;

				margin: 140px auto;
			}

			.amendmsg p{
				font-size: 24px;
			}


		</style>

  </head>

  <body>
  	<div class="amendmsg">
	  	<p style="color: green"><%= flash[:notice] %></p>
			<p style="color: red"><%= flash[:alert] %></p>
		</div>
    <%= yield %>
  </body>
</html>

todo_list/app/views/todos/_form.html.erb
	<div class="errorbox">
		<% if @todo.errors.any? %>
			<h2>We have some errors here !</h2>
				<ul class="errorlist">
			  	<% @todo.errors.full_messages.each do |msg| %>
			  		<li><%= msg %></li>
			  	<% end %>
				</ul>
			<% end %>
	</div>

	<div class="itembox">
		<%= form_for @todo do |f| %>
			<%= f.label :title, "Title" %>
			<br>
			<%= f.text_area :title %>
			<br>
			<%= f.label :due_date, "Due Date" %>
			<br>
			<%=  f.date_select :due_date %>
			
			<br>

			<div class="itembox_btn">
				<%= f.submit button, :class => "btn btn-success" %>
				<%= link_to 'BACK', todos_path, :class => "btn btn-default" %>
				<br>
			</div>

		<% end %>
	</div>

todo_list/app/views/todos/edit.html.erb
<!-- # <%= form_for @todo do |f| %>
#  	<%= f.label :title, "Title : " %>
#  	<%= f.text_area :title %>

#  	<%= f.label :due_date, "Due Date : " %>
#  	<%= f.text_field :due_date %>	

#  	<%= f.submit %>

# <% end %> -->

<!-- #locals 可修改不同頁面傳到partial時的按鈕文字 -->
<%= render :partial => "form", locals: {button: 'UPDATE'} %> 

todo_list/app/views/todos/index.html.erb
	<div class="listbox">
		<div class="sticker"></div>
		<h1>To Do List</h1>
		<div class="underbar"></div>

		<div class="addbtn">
			<%= link_to 'ADD LIST', new_todo_path, :class => "btn btn-success" %>
		</div>
		
		<div class="list">
			<ul>
				<% @todos.each do |todo| %>
				<li>
					<p class="due_date">Due Date : <%= todo.due_date %></p>
					<p class="title"><%= todo.title %></p>
					
					<div class="actions">
						<%= link_to 'EDIT', edit_todo_path(todo), :class => "btn btn-primary" %>
						<%= link_to 'DEL', todo_path(todo), :class => "btn btn-danger", method: :delete, data:{
								confirm: "Delete this item ?"
							} %>
					</div>

				</li>
				<li class="itembar"></li>
				<% end %>
			</ul>
		</div>


	</div>

todo_list/app/views/todos/new.html.erb
<!-- # <%= form_for @todo do |f| %>
# 	<%= f.label :title, "Title : " %>
# 	<%= f.text_area :title %>

# 	<%= f.label :due_date, "Due Date : " %>
# 	<%= f.text_field :due_date %>	

# 	<%= f.submit %>

# <% end %> -->

<%= render :partial => "form", locals: {button: 'NEW'} %>